

import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/*
 * FrmEs3.java
 *
 * Created on 15 luglio 2008, 18.17
 */



/**
 *
 * @author  local
 */
public class FrmEs3 extends javax.swing.JFrame implements ActionListener
{
    
    private JButton Conta;
    private JLabel label;
    int numero;
    
    /** Creates new form FrmEs3 */
    public FrmEs3() {
        initComponents();
        
        getContentPane().setLayout(new GridLayout(2,1));
        label = new JLabel();
        Conta = new JButton("Conta");
        label.setText("0");
        Conta.addActionListener(this);
        getContentPane().add(label);
        getContentPane().add(Conta);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEs3().setVisible(true);
            }
        });
    }

    public void actionPerformed(ActionEvent e)
    {
        numero++;
        label.setText(String.valueOf(_numero));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
