/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package esercizio_3;

/**
 *
 * @author paolo
 */
public class Finestra extends javax.swing.JFrame {

    /**
     * Creates new form Finestra
     */
    public Finestra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pannello1 = new javax.swing.JPanel();
        Testo1 = new javax.swing.JTextField();
        Testo2 = new javax.swing.JTextField();
        Label = new javax.swing.JLabel();
        Pannello2 = new javax.swing.JPanel();
        Bottone = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Applicazione Confronta");

        Testo1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Testo2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout Pannello1Layout = new javax.swing.GroupLayout(Pannello1);
        Pannello1.setLayout(Pannello1Layout);
        Pannello1Layout.setHorizontalGroup(
            Pannello1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pannello1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Testo1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(Testo2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        Pannello1Layout.setVerticalGroup(
            Pannello1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pannello1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(Pannello1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Testo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Testo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        getContentPane().add(Pannello1, java.awt.BorderLayout.PAGE_START);

        Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label.setText("Clicca sul pulsante");
        getContentPane().add(Label, java.awt.BorderLayout.PAGE_END);

        Bottone.setText("Confronta");
        Bottone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Pannello2Layout = new javax.swing.GroupLayout(Pannello2);
        Pannello2.setLayout(Pannello2Layout);
        Pannello2Layout.setHorizontalGroup(
            Pannello2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pannello2Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(Bottone, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        Pannello2Layout.setVerticalGroup(
            Pannello2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pannello2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(Bottone, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        getContentPane().add(Pannello2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BottoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottoneActionPerformed
        String s1,s2;
        s1=Testo1.getText();
        s2=Testo2.getText();
        if(s1.equals(s2))
            Label.setText("UGUALI");
        else
            Label.setText("DIVERSI");
    }//GEN-LAST:event_BottoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Finestra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bottone;
    private javax.swing.JLabel Label;
    private javax.swing.JPanel Pannello1;
    private javax.swing.JPanel Pannello2;
    private javax.swing.JTextField Testo1;
    private javax.swing.JTextField Testo2;
    // End of variables declaration//GEN-END:variables
}
