
package esercizio3;


public class FinestraEsercizio3 extends javax.swing.JFrame {

    /** Creates new form FinestraEsercizio3 */
    public FinestraEsercizio3() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bottoneSinistra = new javax.swing.JButton();
        etichettaDirezioni = new javax.swing.JLabel();
        bottoneDestra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Esercizio Tre");
        getContentPane().setLayout(new java.awt.FlowLayout());

        bottoneSinistra.setText("Sinistra");
        bottoneSinistra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottoniActionPerformed(evt);
            }
        });
        getContentPane().add(bottoneSinistra);

        etichettaDirezioni.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etichettaDirezioni.setPreferredSize(new java.awt.Dimension(100, 14));
        getContentPane().add(etichettaDirezioni);

        bottoneDestra.setText("Destra");
        bottoneDestra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottoniActionPerformed(evt);
            }
        });
        getContentPane().add(bottoneDestra);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void bottoniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottoniActionPerformed
        javax.swing.JButton b = (javax.swing.JButton) evt.getSource();
        etichettaDirezioni.setText(b.getText());
    }//GEN-LAST:event_bottoniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FinestraEsercizio3().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bottoneDestra;
    private javax.swing.JButton bottoneSinistra;
    private javax.swing.JLabel etichettaDirezioni;
    // End of variables declaration//GEN-END:variables
}
